### ISSUE TITLE
Content Issue 1: Fix Content in Sitemap

### ISSUE THREAD

**Issue by asibole1** [Weiyeahh/Steyy-Website#1]
Hi Weiye, 

I wanted to bring to your attention that there are a couple of minor spelling errors here on the sitemap: 

https://github.com/Weiyeahh/Steyy-Website/blob/aa518f03588099fd8ff22d4f481149fcb4aeb5d2/templates/sitemap.html#L41-L43

"Information" and "Contact Us"

Quick fix but definitely will bring more professionalism to the site :)

**Comment by Weiyeahh** [comment]
Thanks! made that in a rush!
