### ISSUE TITLE
Technical Issue 1: Telephone Number href Not Working

### ISSUE THREAD

**Issue by asibole1** [Weiyeahh/Steyy-Website#2]
Hi Weiye, 

You did a great job with the contact page! Love the iframe with the location, that was a great addition. I wanted to let you know that when I click the phone number for contact, it brings me to a "Not Found" error: 

https://github.com/Weiyeahh/Steyy-Website/blob/aa518f03588099fd8ff22d4f481149fcb4aeb5d2/templates/contactus.html#L44

[According to this article I found](https://www.elegantthemes.com/blog/wordpress/call-link-html-phone-number#:~:text=Adding%20an%20HTML%20Phone%20Number%20Call%20Link%20to%20your%20Website&text=Href%3Dtel%3A%20creates%20the%20call,the%20number%20it%20will%20call.), I think in order to fix this you just need to add a colon in place of the space after "tel". 

Great work!

**Comment by Weiyeahh** [comment]
thanks! I added a colon and it worked!
