### ISSUE TITLE
Content Issue 2: Suggestion to Make Headers Match

### ISSUE THREAD

**Issue by asibole1** [Weiyeahh/Steyy-Website#3]
Hi Weiye, 

I LOVE the overall design of the site. I would suggest, though, to create a more cohesive user experience, to make the home page header match the header that appears on the other pages. 

Here's the homepage header I am referencing: https://steyy.com/

Compared to the header on this page, for instance: https://steyy.herokuapp.com/usercase

To fix this you could just use the css code you used in one in the other. I would add that here but I couldn't seem to find your .css file. 

Hope this is helpful!

**Comment by Weiyeahh** [comment]
done! thanks！
