### ISSUE TITLE
Technical Issue 2: Broken Links on SiteMap

### ISSUE THREAD

**Issue by asibole1** [Weiyeahh/Steyy-Website#4]
Hi Weiye, 

I found a few broken links on your Sitemap that you may want to update: 
https://github.com/Weiyeahh/Steyy-Website/blob/aa518f03588099fd8ff22d4f481149fcb4aeb5d2/templates/sitemap.html#L35-L39

I do love how you broke this up into two sections! Great work.

**Comment by Weiyeahh** [comment]
fixed, thx!
