### ISSUE TITLE
Project peer review: Dylan Haddad

### ISSUE THREAD

**Issue by narluku** [Weiyeahh/Steyy-Website#5]
Suggestions on content:

Hey Weiye! I loved your website, it is really ingenious. 

1- The sitemap page could be a bit better aesthetically, you could maybe try and make it more interactive since there are important links on there. Also, there are plenty of vocabulary errors. Such as the information page and contact us links.

2- Adding an information page where you could add statistics on how AI can help people with their problems and emotions on a daily basis. Statistics could push people to use your website more regularly.

Technical issues:

1-  the href links from 35 to 44 lead to nowhere and are broken. You might want to check up and fix them. 
      
<a href="my-form.html">Tryit-form page</a>
    <a href="chathistory.html">Upload-Chathistory</a>
    <a href="userprofileupload.html">Upload-Userprofile</a>
    <a href="botprofile.html">Upload-botpicture</a>
    <a href="index.html">Chatbot page</a>
    </div>
    <h1 id="ip">Informatin Page</h1>
    <div id="info">
    <a href="contactus.html">Contac us</a>
    <a href="usercase.html">Usercase</a> 

2-  You should maybe not use data list, maybe use radio option so that when you click on one of the options and want to change it, all three options are apparent. I noticed that when clicking one of the options and clicking again, only that option appeared and not the other two.
<datalist id="product">
                    <option>Very Much</option>
                    <option> A lot!</option>
                    <option>It's okay</option>
                </datalist>

**Comment by Weiyeahh** [comment]
hi thanks dylan! I have made changes according to your comment!
